export {
  categoryRegistryKeySchema,
  DECISION_CATEGORY_KEYS,
  getCategoryDescription,
  getCategoryFilterLabels,
  getCategoryFilterOptions,
  getCategoryLabel,
  getCategoryPromptGuidance,
  getCategoryPromptWhitelist,
  getCategorySlug,
  matchesDecisionCategoryFilter,
  normalizeCategory,
  type DecisionCategory,
  type DecisionCategoryFilter,
  type DecisionCategorySlug,
} from "@/lib/categories/registry";
